### ISSUE TITLE
bug: Error synching when using an alias which gets "slugged"

### ISSUE THREAD

**Issue by jjmu15** [spherehq/sphere#46]
# Bug Report
Error synching after creating a sphere.

**Package version:**

**Current behavior:**

Error Synching.
(node:9085) UnhandledPromiseRejectionWarning: Error: No Node for the model Sphere with value PolkadotTest for alias found.

**Expected behavior:**
Articles and content syncs to sphere

**Steps to reproduce:**

sphere init
alias = PolkadotTest
create dir called test within PolkadotTest
add file called test.md within test dir
attempt sphere sync

**Other information:**

A Designer’s Guide To Better Decisions https://sphere.sh/@PolkadotTest/test 
(node:9085) UnhandledPromiseRejectionWarning: Error: No Node for the model Sphere with value PolkadotTest for alias found.
    at BatchedGraphQLClient.<anonymous> (/Users/jamiemurphy/.nvm/versions/node/v12.1.0/lib/node_modules/@spherehq/cli/node_modules/http-link-dataloader/dist/src/BatchedGraphQLClient.js:77:35)
    at step (/Users/jamiemurphy/.nvm/versions/node/v12.1.0/lib/node_modules/@spherehq/cli/node_modules/http-link-dataloader/dist/src/BatchedGraphQLClient.js:40:23)
    at Object.next (/Users/jamiemurphy/.nvm/versions/node/v12.1.0/lib/node_modules/@spherehq/cli/node_modules/http-link-dataloader/dist/src/BatchedGraphQLClient.js:21:53)
    at fulfilled (/Users/jamiemurphy/.nvm/versions/node/v12.1.0/lib/node_modules/@spherehq/cli/node_modules/http-link-dataloader/dist/src/BatchedGraphQLClient.js:12:58)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
(node:9085) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:9085) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by jjaybrown** [comment]
thanks @jjmu15 I think the problem is internally the alias gets "slugged" which removes the capitalisation and creates a separation between camel-cased words.

So PolkadotTest becomes polkadot-test which may not be transformed consistently across the CLI commands.

Will add to list of fixes.
